services:
  overcraft-frontend:
    extends:
      file: docker-services.yml
      service: overcraft-frontend
  overcraft-backend:
    extends:
      file: docker-services.yml
      service: overcraft-backend
  overcraft-database:
    extends:
      file: docker-services.yml
      service: overcraft-database
  overcraft-pgadmin:
    extends:
      file: docker-services.yml
      service: overcraft-pgadmin
  overcraft-nginx:
    extends:
      file: docker-services.yml
      service: overcraft-nginx
    networks:
      - vps_nginx_default

networks:
  overcraft:
    name: overcraft
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
  vps_nginx_default:
    name: vps_nginx_default
    external: true

volumes:
  pgdata:


